-- MySQL Script generated by MySQL Workbench
-- Wed Sep  9 11:41:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sales
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sales` ;

-- -----------------------------------------------------
-- Schema sales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sales` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sales` ;

-- -----------------------------------------------------
-- Table `sales`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales`.`customers` ;

CREATE TABLE IF NOT EXISTS `sales`.`customers` (
  `customerNumber` INT NOT NULL,
  `customerName` VARCHAR(50) NOT NULL,
  `contactLastName` VARCHAR(50) NOT NULL,
  `contactFirstName` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `addressLine1` VARCHAR(50) NOT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `creditLimit` DOUBLE NULL DEFAULT NULL,
  `employeeNumber` INT NULL DEFAULT NULL,
  PRIMARY KEY (`customerNumber`),
  INDEX `employeeNumber` (`employeeNumber` ASC) VISIBLE,
  CONSTRAINT `customers_ibfk_1`
    FOREIGN KEY (`employeeNumber`)
    REFERENCES `sales`.`employees` (`employeeNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sales`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales`.`employees` ;

CREATE TABLE IF NOT EXISTS `sales`.`employees` (
  `employeeNumber` INT NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `jobTitle` VARCHAR(50) NOT NULL,
  `officeCode` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`employeeNumber`),
  INDEX `officeCode` (`officeCode` ASC) VISIBLE,
  CONSTRAINT `employees_ibfk_1`
    FOREIGN KEY (`officeCode`)
    REFERENCES `sales`.`offices` (`officeCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sales`.`offices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales`.`offices` ;

CREATE TABLE IF NOT EXISTS `sales`.`offices` (
  `officeCode` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `addressLine1` VARCHAR(50) NOT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`officeCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sales`.`orderdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales`.`orderdetails` ;

CREATE TABLE IF NOT EXISTS `sales`.`orderdetails` (
  `productCode` VARCHAR(15) NOT NULL,
  `orderNumber` INT NOT NULL,
  INDEX `productCode` (`productCode` ASC) VISIBLE,
  INDEX `orderNumber` (`orderNumber` ASC) VISIBLE,
  CONSTRAINT `orderdetails_ibfk_1`
    FOREIGN KEY (`productCode`)
    REFERENCES `sales`.`products` (`productCode`),
  CONSTRAINT `orderdetails_ibfk_2`
    FOREIGN KEY (`orderNumber`)
    REFERENCES `sales`.`orders` (`orderNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sales`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales`.`orders` ;

CREATE TABLE IF NOT EXISTS `sales`.`orders` (
  `orderNumber` INT NOT NULL,
  `orderDate` DATE NOT NULL,
  `requiredDate` DATE NOT NULL,
  `shippedDate` DATE NULL DEFAULT NULL,
  `status` VARCHAR(15) NOT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `quantityOrder` INT NOT NULL,
  `priceEach` DOUBLE NOT NULL,
  `customerNumber` INT NULL DEFAULT NULL,
  PRIMARY KEY (`orderNumber`),
  INDEX `customerNumber` (`customerNumber` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `sales`.`customers` (`customerNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sales`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales`.`payments` ;

CREATE TABLE IF NOT EXISTS `sales`.`payments` (
  `checkNumber` VARCHAR(50) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `amount` DOUBLE NOT NULL,
  `customerNumber` INT NULL DEFAULT NULL,
  INDEX `customerNumber` (`customerNumber` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `sales`.`customers` (`customerNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sales`.`productlines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales`.`productlines` ;

CREATE TABLE IF NOT EXISTS `sales`.`productlines` (
  `productLine` VARCHAR(50) NOT NULL,
  `textDescription` TEXT NULL DEFAULT NULL,
  `image` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`productLine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sales`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales`.`products` ;

CREATE TABLE IF NOT EXISTS `sales`.`products` (
  `productCode` VARCHAR(15) NOT NULL,
  `productName` VARCHAR(70) NOT NULL,
  `productScale` VARCHAR(10) NOT NULL,
  `productVendor` VARCHAR(50) NOT NULL,
  `productDescription` TEXT NOT NULL,
  `quantityInStock` INT NOT NULL,
  `buyPrice` DOUBLE NOT NULL,
  `MSRP` DOUBLE NOT NULL,
  `productLine` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`productCode`),
  INDEX `productLine` (`productLine` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`productLine`)
    REFERENCES `sales`.`productlines` (`productLine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
